export * from "./enviroment.interface";
export * from "./user.interface";
export * from "./model.interface";
export * from "./lesson.interface";
export * from "./role.interface";
export * from "./exercise.interface";
export * from "./course.interface";
export * from "./common.interface";
export * from "./collection.interface";
